import Head from 'next/head'
import Image from 'next/image'
import { useContext, useEffect } from 'react'
import { UserContext } from '@/context/context'
import {User} from '../utils/types'
import Products from '@/components/products/Products'

export default function Home(props: { user: User }) {

  const {user,setUserState,setIsLoading,loading} = useContext(UserContext)

  useEffect(() => {
    setUserState(props.user)
    setIsLoading(false)
    
  }, [])

  if (loading) {
    return <div>Loading...</div>
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products/>

    </>
  )
}

export async function getStaticProps(){

  const data = await fetch('https://coding-challenge-api.aerolab.co/user/me',{
    headers:{
      'Content-Type' : 'application/json',
      'Accept': 'application/json',
      'Authorization': `Bearer ${process.env.NEXT_PUBLIC_API_TOKEN}`
    }
  })

  const res = await data.json()


  return {
    props: {                      
      user: {
        ...res
      },
    },            
  }; 
}